services:
    auth-server:
        image: nginx:latest
        container_name: auth-server
        ports:
          - 8021:80
        volumes:
          - ./docker/nginx/conf.d/auth/default.conf:/etc/nginx/conf.d/default.conf
          - ./backend/auth:/var/www/html
        depends_on:
          - auth-php
    
    catalog-server:
        image: nginx:latest
        container_name: catalog-server
        ports:
          - 8022:80
        volumes:
          - ./docker/nginx/conf.d/catalog/default.conf:/etc/nginx/conf.d/default.conf
          - ./backend/catalog:/var/www/html
        depends_on:
          - catalog-php
    
    checkout-server:
        image: nginx:latest
        container_name: checkout-server
        ports:
          - 8023:80
        volumes:
          - ./docker/nginx/conf.d/checkout/default.conf:/etc/nginx/conf.d/default.conf
          - ./backend/checkout:/var/www/html
        depends_on:
          - checkout-php
    
    auth-php:
        build: ./docker/php
        container_name: auth-php
        volumes:
          - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
          - ./backend/auth:/var/www/html
    
    catalog-php:
        build: ./docker/php
        container_name: catalog-php
        volumes:
          - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
          - ./backend/catalog:/var/www/html
    
    checkout-php:
        build: ./docker/php
        container_name: checkout-php
        volumes:
          - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
          - ./backend/checkout:/var/www/html
    
    messaging:
        image: rabbitmq:3-management
        container_name: messaging
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password


#  database:
#    image: mysql:8.3.0
#    container_name: ${DB_CONTAINER_NAME}
#    ports:
#      - ${MYSQL_PORT}:3306
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
