services:
    auth-server:
        image: nginx:latest
        ports:
        - ${AUTH_SERVER_PORT}:80
        volumes:
        - ./docker/nginx/conf.d/auth.conf:/etc/nginx/conf.d/default.conf
        - ./backend/auth:/var/www/html
        depends_on:
        - app

    catalog-server:
        image: nginx:latest
        ports:
        - ${CATALOG_SERVER_PORT}:80
        volumes:
        - ./docker/nginx/conf.d/catalog.conf:/etc/nginx/conf.d/default.conf
        - ./backend/catalog:/var/www/html
        depends_on:
        - app

    checkout-server:
        image: nginx:latest
        ports:
        - ${CHECKOUT_SERVER_PORT}:80
        volumes:
        - ./docker/nginx/conf.d/checkout.conf:/etc/nginx/conf.d/default.conf
        - ./backend/checkout:/var/www/html
        depends_on:
        - app

    app:
        build: ./docker/php
        volumes:
        - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./:/var/www/html